services:
  mistral_instruct_7b:
    build:
      context: ./build
    ports:
      - 5285:5000
    restart: unless-stopped
    networks:
      - demo_network
    container_name: mistral_instruct_7b_container
    image: mistral_instruct_7b_image
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  demo_network:
    external: true
