services:
  vicuna:
    build:
      context: ./build
    ports:
      - 5287:5000
    restart: unless-stopped
    networks:
      - demo_network
    container_name: vicuna_container
    image: vicuna_image

networks:
  demo_network:
    external: true
