services:
  vicuna:
    build:
      context: ./build
    ports:
      - 5285:5285
    restart: unless-stopped
    networks:
      - turbo_network
    container_name: vicuna_container
    image: vicuna_image
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    depends_on:
      - controller
      - worker

  worker:
    build:
      context: ./workers
    ports:
      - 5288:5288
    restart: unless-stopped
    networks:
      - turbo_network
    container_name: vicuna_worker
    image: vicuna_worker_image
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    depends_on:
      - controller

  controller:
    build:
      context: ./controllers
    ports:
      - 5287:5287
    restart: unless-stopped
    networks:
      - turbo_network
    container_name: vicuna_controller
    image: vicuna_controller_image


networks:
  turbo_network:
    external: false
