services:
  vicuna:
    build:
      context: ./build
    ports:
      - 5287:5000
    restart: unless-stopped
    networks:
      - demo_network
    container_name: vicuna_container
    image: vicuna_image
    volumes:
      - /coypu/static-data/models/:/data/models/
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [ gpu ]

networks:
  demo_network:
    external: true
